In [1]:
import functions

In [2]:
import numpy as np

In [3]:
data = functions.generate_data(100, 2, 2, 0.5, 10)

In [4]:
data_mcar = functions.generate_data_MCAR(data, 0.1)
data_mcar

(array([[ 2.79425700e+00,  4.59309913e+00,  5.92007659e+00,
          7.70263073e+00,  9.14505923e+00,  1.08002148e+01,
          1.22956823e+01,  1.39944046e+01,  1.59016680e+01,
          1.73153601e+01],
        [ 2.08924745e+00,  4.29225739e+00,  7.02873096e+00,
          9.76312684e+00,  1.23284821e+01,  1.51376353e+01,
          1.73435063e+01,  2.01080990e+01,  2.28720980e+01,
          2.53790388e+01],
        [ 6.98095851e-01,  3.40049070e+00,  5.88159173e+00,
          8.17625839e+00,  1.02546795e+01,  1.29218521e+01,
          1.53472921e+01,  1.73845728e+01,  1.98809848e+01,
          2.21584461e+01],
        [ 1.85233854e+00,  5.08686120e+00,  8.12906579e+00,
          1.09555630e+01,  1.41413191e+01,  1.72634338e+01,
          2.02379369e+01,  2.32865838e+01,  2.62778048e+01,
          2.91033465e+01],
        [ 3.37264388e+00,             nan,  7.95220871e+00,
          1.09544336e+01,  1.32192348e+01,  1.59526664e+01,
          1.83392783e+01,  2.05870666e+01,  2.327002

In [9]:
functions.CCA(data_mcar)[0]

[array([ 2.794257  ,  4.59309913,  5.92007659,  7.70263073,  9.14505923,
        10.80021477, 12.29568227, 13.99440462, 15.90166804, 17.31536014]),
 array([ 2.08924745,  4.29225739,  7.02873096,  9.76312684, 12.32848209,
        15.13763532, 17.34350627, 20.10809901, 22.87209802, 25.37903884]),
 array([ 0.69809585,  3.4004907 ,  5.88159173,  8.17625839, 10.25467954,
        12.92185206, 15.34729213, 17.38457279, 19.88098484, 22.15844613]),
 array([ 1.85233854,  5.0868612 ,  8.12906579, 10.95556303, 14.14131914,
        17.26343382, 20.23793693, 23.28658376, 26.27780475, 29.1033465 ]),
 array([ 1.32596999,  2.72990398,  3.56770079,  5.02331449,  6.41044847,
         7.45095611,  8.55751749,  9.98961453, 11.03159981, 12.36992929]),
 array([ 1.96644614,  5.14902448,  7.73766983, 10.94265499, 13.32698626,
        16.56840156, 19.1225137 , 22.38783257, 24.72398448, 27.91780485]),
 array([ 4.77700017,  7.95102486, 11.76602442, 15.73784401, 19.45626698,
        23.32537585, 27.09208075, 30.97